### PR TITLE
Add dockerfile

### PR DESCRIPTION
**Pull request by thetooth**
Only builds and runs the nyaa binary, you have to provide the DB yourself.

### CODE REVIEW

**Comment by Atvaark** [comment]
The deps don't look up to date with https://github.com/ewhal/nyaa/blob/83e496a224b2c22dec4173017ed3496bf7cff06f/.travis.yml.

**Comment by thetooth** [comment]
@Atvaark updated, pls test

**Comment by ewhal** [comment]
no need for this right now

**Comment by akuma06** [comment]
According to my anon on the IRC, we have already a docker file. We appreciate the new approach and might use it later

**Pull request closed without merging**
