### PR TITLE
Show date created for comments. (don't merge yet!!!)

### PR DESCRIPTION
**Pull request by TUSF**
Hopefully I didn't break something. I don't normally use Bootstrap.

### CODE REVIEW

**Comment by ayame-git** [comment]
borked i think

**Comment by ayame-git** [comment]
O-o-ok

**Comment by aerojun** [comment]
I don't know if it's because i'm using the sqlite db but i get the following error:

`ERRO[0001] ViewHandler(): template: view.html:97:36: executing "content" at <.CreatedAt.Year>: can't evaluate field CreatedAt in type model.CommentJSON`

**Comment by TUSF** [comment]
@aerojun Crap; I used the wrong model, and thus the wrong field name. Hold up.

**Pull request merged**
