### PR TITLE
Bringing back megumin

### PR DESCRIPTION
**Pull request by S0X-LT**
dunno if this works, but compared it to style.css and it should work.

### CODE REVIEW

**Comment by alucard0134** [comment]
test if it works first pls

**Comment by kipukun** [comment]
you piece of shit don't use css backgrounds it's impossible to work with

**Comment by kipukun** [comment]
And Megumeme is already in the latest HEAD. This can be closed.
fucking

**Comment by S0X-LT** [comment]
alright then

**Pull request closed without merging**
