### PR TITLE
Small changes on view template

### PR DESCRIPTION
**Pull request by kipukun**
Added a big download button
Remove torrent id
Border-less table for more organic information display
Small ``<hr>`` below search to better separate content

### CODE REVIEW

**Comment by sfan5** [comment]
>15 merge commits

wew lad

**Comment by akuma06** [comment]
Because it might not be user friendly, I guess... If someone wants it, it is in the url anyway.

**Comment by kipukun** [comment]
I'm possibly mentally ill, so that's the only way I know how to rebase is by pulling from upstream and pushing to my fork.

**Comment by sfan5** [comment]
Doing rebases shouldn't give you merge commits :thinking:
Also you accidentally added a `nyaa-master` file

**Pull request merged**
